Hot fix/edit room
COS301-SE-2024/TuneIn pull request #235
Opened 2024-09-06 09:59 UTC by thabisomatau

## Description
[Describe the purpose of this pull request]

## Type of Change
- [x] Bug fix
- [ ] New feature
- [ ] Documentation
- [ ] Refactor
- [ ] Other: (summarise briefly here)

## Changes Made
EditRoom now works

## Does this break anything? (Modifying more expected behaviour/layout, etc)
- [ ] Yes
- [x] No

## Screenshots (if applicable)
![image](https://github.com/user-attachments/assets/834d47fb-ee5b-48d1-96c5-015a91a9141f)
## Performance Implications
[Discuss any potential performance implications or improvements]

## Related Issues
https://github.com/COS301-SE-2024/TuneIn/234
## Dependencies
[List any new dependencies or updates]

## Checklist
- [x] I have tested this code locally
- [x] I have reviewed the code for readability and maintainability
- [x] I have added appropriate documentation or updated existing documentation
- [x] I have ensured that my changes follow the project's coding conventions
- [x] I have performed additional steps, if required [e.g., database migrations, configuration changes, etc.]

## Additional Notes
[Include any additional notes or context relevant to the pull request]

## (ignore) A checklist for the reviewer to use
```
## Reviewer Checklist
- [ ] Code quality and readability
- [ ] Adequate documentation
- [ ] Follows project coding conventions
- [ ] Considered security implications
- [ ] Considered accessibility implications
- [ ] Considered performance implications
- [ ] Tested locally
```

2024-09-06 10:33 UTC, lkekana approved these changes

2024-09-06 10:33 UTC, lkekana commented
@Linda-Masia will you check the frontend?

2024-09-08 06:39 UTC, Linda-Masia requested changes
Add a test for EditRoom.tsx

2024-09-08 08:21 UTC, Linda-Masia approved these changes

2024-09-08 08:29 UTC, merged